routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PelangganController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::get('/pelanggan/index', function () {
//     return view('pelanggan.index');
// });
// Route::get('/pelanggan/show', function () {
//     return view('pelanggan.show');
// });
// Route::get('/admin/dashboard', function () {
//     return view('admin.dashboard');
// });
// Route::get('/admin/kategori/index', function () {
//     return view('admin.kategori.index');
// });
// Route::get('/admin/kategori/create', function () {
//     return view('admin.kategori.create');
// });
// Route::get('/admin/kategori/create', function () {
//     return view('admin.kategori.edit');
// });
// Route::get('/admin/product/index', function () {
//     return view('admin.product.index');
// });
// Route::get('/admin/product/create', function () {
//     return view('admin.product.create');
// });
// Route::get('/admin/product/edit', function () {
//     return view('admin.product.edit');
// });


// Routes for Categories


Route::get('/products', [PelangganController::class, 'index']);
Route::get('/pelanggan/{id}', [PelangganController::class, 'show'])->name('pelanggan.show');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/*------------------------------------------
--------------------------------------------
All Normal Users Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:user'])->group(function () {


    Route::get('/products', [PelangganController::class, 'index']);
    Route::get('/pelanggan/{id}', [PelangganController::class, 'show'])->name('pelanggan.show');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

/*------------------------------------------
--------------------------------------------
All Admin Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:admin'])->group(function () {

    Route::resource('categories', CategoryController::class);

    Route::get('/admin/kategori', [CategoryController::class, 'index'])->name('admin.kategori.index');

    // Routes for Menus
    Route::resource('menus', MenuController::class);


    Route::get('/admin/menu', [MenuController::class, 'index'])->name('admin.menu.index');
    Route::get('/products', [PelangganController::class, 'index']);
    Route::get('/pelanggan/{id}', [PelangganController::class, 'show'])->name('pelanggan.show');
});

/*------------------------------------------
--------------------------------------------
All Admin Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:manager'])->group(function () {

    Route::resource('categories', CategoryController::class);

    Route::get('/admin/kategori', [CategoryController::class, 'index'])->name('admin.kategori.index');

    // Routes for Menus
    Route::resource('menus', MenuController::class);


    Route::get('/admin/menu', [MenuController::class, 'index'])->name('admin.menu.index');
    Route::get('/products', [PelangganController::class, 'index']);
});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'price', 'description', 'image', 'category_id'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Menu;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class MenuController extends Controller
{
    public function index()
    {
        $menus = Menu::with('category')->get();
        return view('admin.menu.index', compact('menus'));
    }

    public function create()
    {
        $createmenus = Category::all();
        return view('admin.menu.create', compact('createmenus'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'name' => 'required',
            'price' => 'required',
            'description' => 'required',
            'category_id' => 'required'
        ]);

        $image = $request->file('image');
        $imageName = time() . '.' . $image->extension();
        $image->storeAs('public/menu_images', $imageName);

        Menu::create([
            'image' => $imageName,
            'name' => $request->name,
            'price' => $request->price,
            'description' => $request->description,
            'category_id' => $request->category_id
        ]);

        return redirect()->route('menus.index')->with('success', 'Menu berhasil ditambahkan');
    }

    public function edit($id)
    {
        $menu = Menu::findOrFail($id);
        $categories = Category::all();
        return view('admin.menu.edit', compact('menu', 'categories'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'description' => 'required',
            'category_id' => 'required'
        ]);

        $menu = Menu::findOrFail($id);

        if ($request->hasFile('image')) {
            $request->validate([
                'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);

            $image = $request->file('image');
            $imageName = time() . '.' . $image->extension();
            $image->storeAs('public/menu_images', $imageName);

            // Delete old image
            if ($menu->image) {
                Storage::delete('public/menu_images/' . $menu->image);
            }

            $menu->image = $imageName;
        }

        $menu->name = $request->name;
        $menu->price = $request->price;
        $menu->description = $request->description;
        $menu->category_id = $request->category_id;
        $menu->save();

        return redirect()->route('menus.index')->with('success', 'Menu berhasil diperbarui');
    }

    public function destroy($id)
    {
        $menu = Menu::findOrFail($id);

        // Delete image
        if ($menu->image) {
            Storage::delete('public/menu_images/' . $menu->image);
        }

        $menu->delete();

        return redirect()->route('menus.index')->with('success', 'Menu berhasil dihapus');
    }
}

resources/views/admin/menu/create.blade.php
@extends('admin.template.layout')

@section('isi')
<div class="container py-5 mt-4">
    <h1>Tambah Menu</h1>
    <form action="{{ route('menus.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group mt-2">
            <label for="name">Nama:</label>
            <input type="text" name="name" id="name" class="form-control">
        </div>
        <div class="form-group mt-2">
            <label for="price">Harga:</label>
            <input type="number" name="price" id="price" class="form-control">
        </div>
        <div class="form-group mt-2">
            <label for="description">Keterangan:</label>
            <textarea name="description" id="description" class="form-control"></textarea>
        </div>
        <div class="form-group mt-2">
            <label for="image">Gambar:</label>
            <input type="file" name="image" id="image" class="form-control-file">
        </div>
        <div class="form-group mt-2">
            <label for="category">Kategori:</label>
            <select name="category_id" id="category" class="form-control">
                @foreach($createmenus as $createmenu)
                <option value="{{ $createmenu->id }}">{{ $createmenu->name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Simpan</button>
    </form>
</div>
@endsection

resources/views/admin/menu/edit.blade.php
@extends('admin.template.layout')
@section('isi')
<div class="container">
    <h1>Edit Menu</h1>
    <form action="{{ route('menus.update', $menu->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Nama:</label>
            <input type="text" name="name" id="name" class="form-control" value="{{ $menu->name }}">
        </div>
        <div class="form-group">
            <label for="price">Harga:</label>
            <input type="number" name="price" id="price" class="form-control" value="{{ $menu->price }}">
        </div>
        <div class="form-group">
            <label for="description">Keterangan:</label>
            <textarea name="description" id="description" class="form-control">{{ $menu->description }}</textarea>
        </div>
        <div class="form-group">
            <label for="image">Gambar:</label>
            <input type="file" name="image" id="image" class="form-control-file">
        </div>
        <div class="form-group">
            <label for="category">Category:</label>
            <select name="category_id" id="category" class="form-control">
                @foreach($categories as $category)
                <option value="{{ $category->id }}" @if($category->id == $menu->category_id) selected
                    @endif>{{ $category->name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
@endsection

resources/views/admin/menu/index.blade.php
@extends('admin.template.layout')

@section('isi')
<div class="container py-5 mt-4">
    <div class="row">
        <div class="col-lg-12">
            <h3>Daftar Menu</h3>
            <a href="{{ route('menus.create') }}" class="btn btn-success">Tambah Menu</a>

            <div class="table-responsive mt-4">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Gambar</th>
                            <th>Nama</th>
                            <th>Harga</th>
                            <th>Keterangan</th>
                            <th>Kategori</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($menus as $menu)
                        <tr>
                            <td>
                                <img src="{{ asset('storage/menu_images/' . $menu->image) }}" alt="{{ $menu->name }}"
                                    width="200">
                            </td>
                            <td>{{ $menu->name }}</td>
                            <td>{{ $menu->price }}</td>
                            <td>{{ $menu->description }}</td>
                            <td>{{ $menu->category->name }}</td>
                            <td>
                                <a href="{{ route('menus.edit', $menu->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                <form action="{{ route('menus.destroy', $menu->id) }}" method="POST" class="d-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm"
                                        onclick="return confirm('Apakah Anda yakin ingin menghapus menu ini?')">Hapus</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>
@endsection