routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PelangganController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::get('/pelanggan/index', function () {
//     return view('pelanggan.index');
// });
// Route::get('/pelanggan/show', function () {
//     return view('pelanggan.show');
// });
// Route::get('/admin/dashboard', function () {
//     return view('admin.dashboard');
// });
// Route::get('/admin/kategori/index', function () {
//     return view('admin.kategori.index');
// });
// Route::get('/admin/kategori/create', function () {
//     return view('admin.kategori.create');
// });
// Route::get('/admin/kategori/create', function () {
//     return view('admin.kategori.edit');
// });
// Route::get('/admin/product/index', function () {
//     return view('admin.product.index');
// });
// Route::get('/admin/product/create', function () {
//     return view('admin.product.create');
// });
// Route::get('/admin/product/edit', function () {
//     return view('admin.product.edit');
// });


// Routes for Categories


Route::get('/products', [PelangganController::class, 'index']);
Route::get('/pelanggan/{id}', [PelangganController::class, 'show'])->name('pelanggan.show');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/*------------------------------------------
--------------------------------------------
All Normal Users Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:user'])->group(function () {


    Route::get('/products', [PelangganController::class, 'index']);
    Route::get('/pelanggan/{id}', [PelangganController::class, 'show'])->name('pelanggan.show');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

/*------------------------------------------
--------------------------------------------
All Admin Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:admin'])->group(function () {

    Route::resource('categories', CategoryController::class);

    Route::get('/admin/kategori', [CategoryController::class, 'index'])->name('admin.kategori.index');

    // Routes for Menus
    Route::resource('menus', MenuController::class);


    Route::get('/admin/menu', [MenuController::class, 'index'])->name('admin.menu.index');
    Route::get('/products', [PelangganController::class, 'index']);
    Route::get('/pelanggan/{id}', [PelangganController::class, 'show'])->name('pelanggan.show');
});

/*------------------------------------------
--------------------------------------------
All Admin Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:manager'])->group(function () {

    Route::resource('categories', CategoryController::class);

    Route::get('/admin/kategori', [CategoryController::class, 'index'])->name('admin.kategori.index');

    // Routes for Menus
    Route::resource('menus', MenuController::class);


    Route::get('/admin/menu', [MenuController::class, 'index'])->name('admin.menu.index');
    Route::get('/products', [PelangganController::class, 'index']);
});

resources/views/admin/kategori/create.blade.php
@extends('admin.template.layout')
@section('isi')
<div class="container py-5 mt-4">
    <h1>Tambah Category</h1>
    <form action="{{ route('categories.store') }}" method="POST">
        @csrf
        <div class="form-group mt-3">
            <label for="name">Nama:</label>
            <input type="text" name="name" id="name" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary mt-3">Simpan</button>
    </form>
</div>
@endsection

resources/views/admin/kategori/edit.blade.php
@extends('admin.template.layout')
@section('isi')
<div class="container">
    <h1>Edit Category</h1>
    <form action="{{ route('categories.update', $category->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Nama:</label>
            <input type="text" name="name" id="name" class="form-control" value="{{ $category->name }}">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
@endsection

resources/views/admin/kategori/index.blade.php
@extends('admin.template.layout')
@section('isi')
<div class="container py-5 mt-4">
    <div class="row">
        <div class="col-lg-12">
            <h3>Category Management</h3>
            <a href="{{ route('categories.create') }}" class="btn btn-success">Tambah Kategori</a>

            <div class="table-responsive mt-4">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Nama</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($categories as $category)
                        <tr>
                            <td>{{ $category->name }}</td>
                            <td>
                                <a href=" {{ route('categories.edit', $category->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                <form action="{{ route('categories.destroy', $category->id) }}" method="POST" class="d-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus?')">Hapus</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>
@endsection